# Generated by Django 5.1.7 on 2025-03-19 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria_id',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_ingreso',
        ),
    ]
