# Generated by Django 5.1.7 on 2025-03-20 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_producto_categoria_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='productos',
        ),
    ]
